pipelines:
    esioci_pipeline:
        group: esioci
        materials:
            mygit:
                git: https://github.com/esioci/esioci.git
        stages:
            - build:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: ls -lahrt
